# Generated by Django 4.0.4 on 2022-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='chapters',
            field=models.IntegerField(default=0),
        ),
    ]
